README.md

Added notes for the issues we encountered regarding nginx.

AUTH-95: Identity Service 0.2

---

README.md
charts/incubator/alfresco-dbp/Chart.yaml
charts/incubator/alfresco-dbp/requirements.yaml
charts/incubator/alfresco-dbp/values.yaml
test/postman/dbp-test-collection.json

DEPLOY-531: Pull in stable alfresco-content-services 1.0.0 in the dbp deployment

---

charts/incubator/alfresco-dbp/Chart.yaml
charts/incubator/alfresco-dbp/requirements.yaml

DEPLOY-564: Share is Unusable Without an SSL Environment

---

README-minikube.md
README.md
charts/incubator/alfresco-dbp/values.yaml

DEPLOY-590: DBP Deployment APS Environment Variables Incorrect

---

charts/incubator/alfresco-dbp/Chart.yaml
charts/incubator/alfresco-dbp/requirements.yaml

DEPLOY-550/DEPLOY-587 : Added ACA as a requirement of the dbp chart

---

README.md

- Formatting changes for Docker for Desktop section

DEPLOY-565

---

README-minikube.md
README.md

-Add initial inistructions for deploying the DBP to Docker for Desktop

[DEPLOY-565] Update instructions for deploying the DBP on Mac

---

README.md

-Add instructions for checking context and updating if needed.

[DEPLOY-604] Add back step to check context when installing docker for desktop

---

README.md

-kubectl not found troubleshooting

[DEPLOY-605] Add troubleshooting tip for kubectl when using docker for desktop

---

README.md
charts/incubator/alfresco-dbp/values.yaml

-Add setting to disable infrastructure provided ActiveMQ

[DEPLOY-613] Multiple ActiveMQ instances are deployed

---

test/postman/dbp-test-collection.json

Added token authentication based SSO tests. 
**Important:** do not merge this to master until AUTH-124 has been merged to it.

AUTH-123: Automated testing of SSO for APS and ACS

---

README-minikube.md
README.md
charts/incubator/alfresco-dbp/requirements.yaml
charts/incubator/alfresco-dbp/templates/NOTES.txt

Removed dependency on activiti-cloud-registry and activiti-api-gateway

DEPLOY-620: Slim Down the Infrastructure Chart

---

README-cfn.md
README-minikube.md
README-prerequisite.md
README.md

- added README-prerequisite.md file and links to it

DEPLOY-635: Prerequisites' software versions and documentation

---

charts/incubator/alfresco-dbp/requirements.yaml

DEPLOY-682: Update Activiti dependencies - Week 2

---

charts/incubator/alfresco-dbp/requirements.yaml

Green build: https://bamboo.alfresco.com/bamboo/browse/PS-ADDT41

DEPLOY-690: Updated activiti-cloud-full-example chart version

---

docker/repository/pom.xml
docker/share/pom.xml

Updated AGS to released version 3.1.0

Auth 304 - Update AGS amp version to 3.1.0

---

charts/incubator/alfresco-dbp/values.yaml

- Reinstated process workspace values

AUTH-345: Include the APS Process Workspace

---

charts/incubator/alfresco-dbp/Chart.yaml

Also, added **_appVersion_** (1.5) per DBP versioning guideline and confirmed by @melahn.

AUTH-365: Updated chart version to use SemVer 2.

---

README-cfn.md
README.md

Added a statement to explain to users that they must use azure databases instead of postgres if using azure

DEPLOY-834: alfresco-infrastructure: Fix azureFile PVC

---

helm/alfresco-dbp/requirements.yaml

- alfresco-content-services:~2.1.0
- alfresco-infrastructure:~4.1.1
- alfresco-process-services:~0.1.5

AUTH-397: Fix DBP Branches

---

README.md
helm/alfresco-dbp/minimal-values.yaml
helm/alfresco-dbp/values.yaml

- Added memory limits
- Increased Share replicas to 1
- Updated namespaces in the secrets command examples

AUTH-398: Cleanup of DBP Docs and Minimal Values

---

README.md

- Added note on downgrading to Helm 2.14.3

DEPLOY-861: DBP Deployment for Mac has an error

---

helm/alfresco-dbp/minimal-values.yaml
helm/alfresco-dbp/templates/NOTES.txt
helm/alfresco-dbp/values.yaml

* Updated minimal values
* Updated notes file to contain APW url
* Fixed APP_CONFIG_OAUTH2_REDIRECT_SILENT_IFRAME_URI in values file

DEPLOY-860: Minor updates after APS upgrade

---

docker/helpers/common-functions.sh
docker/repository/build.sh
docker/share/build.sh

Also, minor refactoring to remove the duplicate scripts.

DEPLOY-921: Added an expiration label to the image build script.

---

CONTRIBUTING.md

-Update the CONTRIBUTING Guidelines

[DEPLOY-504] Create a CLA for the dbp-deployment project
